name: Noda Time
pygments: true

markdown:      redcarpet
markdown_ext:  markdown,mkd,mkdn,md

# The latest released version number and date of release.
latest: 1.1.1
latest_released_on: August 30th 2013
